apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appname }}-svc
  namespace: {{ .Values.env }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
  selector:
    app: {{ .Values.appname }}
